== Infinispan - Spring Boot example

=== Abstract

This example demonstrates how you can use Camel-Infinispan Starter component.

=== Introduction

The example is really simple: put a key/value pair in a remote cache and get the same key.
This example starts an Infinispan server with Infinispan Docker Image, so it can run OOTB.

=== Build and test

You can build and test this example using:

    $ mvn package

=== Run

Start Infinispan container in a separate terminal:

    $ podman run --rm -e USER=admin -e PASS=password -p 11222:11222 -v $PWD/src/test/resources:/user-config/:Z quay.io/infinispan/server:15.1.5.Final -c /user-config/infinispan.xml

You can run this example using:

    $ mvn spring-boot:run

Call the exposed endpoint to save a cache item:

    $ curl -X POST -H "Content-type: text/plain" -d "hello" http://localhost:8080/api/jdg?id=1


And you should see output in the console.

=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/support.html[let us know].

We also love contributors, so
https://camel.apache.org/contributing.html[get involved] :-)

The Camel riders!
